window.DM_TOOLS = {
  edit: {
    title: "Edit PDF",
    heading: "Edit PDF",
    kicker: "Edit",
    desc: "Add text, images or annotations to a PDF. Files stay in your browser.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "edit",
  },
  image: {
    title: "Add Images",
    heading: "Add Images",
    kicker: "Edit",
    desc: "Place photos or graphics onto your PDF pages.",
    accept: "application/pdf,image/png,image/jpeg",
    hint: "PDF or image files",
    workspace: "image",
  },

  watermark: {
    title: "Watermark",
    heading: "Watermark PDF",
    kicker: "Edit",
    desc: "Stamp an image or text over your PDF in your browser.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "watermark",
  },
  "pdf-word": {
    title: "PDF to Word",
    heading: "PDF to Word",
    kicker: "Convert",
    desc: "Convert PDF pages into a Word-friendly document. Runs entirely in your browser.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "pdf-word",
  },
  "pdf-jpg": {
    title: "PDF to JPG",
    heading: "PDF to JPG",
    kicker: "Convert",
    desc: "Convert each PDF page into a JPG or PNG image.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "pdf-jpg",
  },
  "jpg-pdf": {
    title: "JPG to PDF",
    heading: "JPG to PDF",
    kicker: "Convert",
    desc: "Convert JPG images to PDF in seconds. Adjust page order as you like.",
    accept: "image/png,image/jpeg",
    hint: "JPG or PNG images",
    workspace: "jpg-pdf",
  },
  "html-pdf": {
    title: "HTML to PDF",
    heading: "HTML to PDF",
    kicker: "Convert",
    desc: "Paste HTML or upload an HTML file and convert it to PDF in your browser.",
    accept: ".html,.htm,text/html,.txt,text/plain",
    hint: "HTML or TXT files",
    workspace: "html-pdf",
  },
  merge: {
    title: "Merge PDF",
    heading: "Merge PDF",
    kicker: "Organize",
    desc: "Combine PDFs in the order you want with the easiest PDF merger available.",
    accept: "application/pdf",
    hint: "PDF files (select 2 or more)",
    workspace: "merge",
    minFiles: 2,
  },
  split: {
    title: "Split PDF",
    heading: "Split PDF",
    kicker: "Organize",
    desc: "Separate one page or a whole set into independent PDF files.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "split",
  },
  rotate: {
    title: "Rotate PDF",
    heading: "Rotate PDF",
    kicker: "Edit",
    desc: "Rotate your PDFs the way you need them, one page or all pages at once.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "rotate",
  },
  compress: {
    title: "Compress PDF",
    heading: "Compress PDF",
    kicker: "Optimize",
    desc: "Reduce file size while keeping PDF quality as high as possible.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "compress",
  },
  sign: {
    title: "Sign PDF",
    heading: "Sign PDF",
    kicker: "Security",
    desc: "Upload a PDF or JPG, then draw or drop a signature onto any page.",
    accept: "application/pdf,image/png,image/jpeg",
    hint: "PDF or JPG files",
    workspace: "sign",
  },
  protect: {
    title: "Protect PDF",
    heading: "Protect PDF",
    kicker: "Security",
    desc: "Encrypt PDF files with a password using AES-256 in your browser.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "protect",
  },
  unlock: {
    title: "Unlock PDF",
    heading: "Unlock PDF",
    kicker: "Security",
    desc: "Remove a known PDF password so you can use the file freely.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "unlock",
  },
  convert: {
    title: "Convert PDF",
    heading: "Convert PDF",
    kicker: "Convert",
    desc: "Convert PDF pages to images, or turn images into a PDF.",
    accept: "application/pdf,image/png,image/jpeg",
    hint: "PDF or image files",
    workspace: "convert",
  },
  organize: {
    title: "Organize PDF",
    heading: "Organize PDF",
    kicker: "Organize",
    desc: "Sort, delete or rearrange pages however you like.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "organize",
  },
  extract: {
    title: "Extract pages",
    heading: "Extract pages",
    kicker: "Organize",
    desc: "Extract selected pages into a new PDF file.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "extract",
  },
  remove: {
    title: "Remove pages",
    heading: "Remove pages",
    kicker: "Organize",
    desc: "Delete unwanted pages and download the updated PDF.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "remove",
  },
  repair: {
    title: "Repair PDF",
    heading: "Repair PDF",
    kicker: "Optimize",
    desc: "Rebuild a damaged PDF by copying readable pages into a new file.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "repair",
  },
  pagenumbers: {
    title: "Page numbers",
    heading: "Page numbers",
    kicker: "Edit",
    desc: "Add page numbers into PDFs. Choose position after opening the file.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "pagenumbers",
  },
  crop: {
    title: "Crop PDF",
    heading: "Crop PDF",
    kicker: "Edit",
    desc: "Crop margins of PDF pages, then apply to one page or the whole file.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "crop",
  },
  redact: {
    title: "Redact PDF",
    heading: "Redact PDF",
    kicker: "Security",
    desc: "Cover sensitive areas with black boxes before you download.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "redact",
  },
};
