window.DM_TOOLS = {
  edit: {
    title: "Edit Text",
    heading: "EDIT TEXT",
    kicker: "Edit",
    desc: "Add or overlay text on your PDF pages. Upload a file, then place text in the workspace.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "edit",
    accent: "t-green",
  },
  image: {
    title: "Add Images",
    heading: "ADD IMAGES",
    kicker: "Edit",
    desc: "Place photos or graphics onto your PDF.",
    accept: "application/pdf,image/png,image/jpeg",
    hint: "PDF or image files",
    workspace: "image",
    accent: "t-green",
  },
  annotate: {
    title: "Annotate",
    heading: "ANNOTATE PDF",
    kicker: "Edit",
    desc: "Mark up pages with text and images. Upload a PDF to start annotating.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "edit",
    accent: "t-green",
  },
  watermark: {
    title: "Watermark",
    heading: "WATERMARK PDF",
    kicker: "Edit",
    desc: "Stamp a watermark on every page. Upload a PDF, then add text or an image overlay.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "edit",
    accent: "t-green",
  },
  "pdf-word": {
    title: "PDF to Word",
    heading: "PDF TO WORD",
    kicker: "Convert",
    desc: "Convert PDF pages into a Word-friendly document. Runs entirely in your browser.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "pdf-word",
    accent: "t-steel",
  },
  "pdf-jpg": {
    title: "PDF to JPG",
    heading: "PDF TO JPG",
    kicker: "Convert",
    desc: "Export each PDF page as a JPG or PNG image. No upload to a server.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "convert",
    accent: "t-steel",
  },
  "jpg-pdf": {
    title: "JPG to PDF",
    heading: "JPG TO PDF",
    kicker: "Convert",
    desc: "Turn one or more JPG / PNG images into a single PDF.",
    accept: "image/png,image/jpeg",
    hint: "JPG or PNG images",
    workspace: "jpg-pdf",
    accent: "t-steel",
  },
  merge: {
    title: "Merge PDF",
    heading: "MERGE PDF",
    kicker: "Organize",
    desc: "Combine two or more PDF files into one document. Select multiple files below.",
    accept: "application/pdf",
    hint: "PDF files (select 2 or more)",
    workspace: "merge",
    accent: "t-pink",
    minFiles: 2,
  },
  split: {
    title: "Split PDF",
    heading: "SPLIT PDF",
    kicker: "Organize",
    desc: "Split a PDF into separate files or extract selected pages.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "split",
    accent: "t-blue",
  },
  rotate: {
    title: "Rotate PDF",
    heading: "ROTATE PDF",
    kicker: "Organize",
    desc: "Rotate pages left or right, then download the updated PDF.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "rotate",
    accent: "t-mint",
  },
  compress: {
    title: "Compress PDF",
    heading: "COMPRESS PDF",
    kicker: "Organize",
    desc: "Rebuild your PDF with compressed streams to reduce file size.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "compress",
    accent: "t-rose",
  },
  sign: {
    title: "Sign Document",
    heading: "SIGN DOCUMENT",
    kicker: "Sign",
    desc: "Draw a signature and place it on any page. Fully client-side.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "sign",
    accent: "t-orange",
  },
  "request-sign": {
    title: "Request Signature",
    heading: "REQUEST SIGNATURE",
    kicker: "Sign",
    desc: "Prepare a PDF for signing. Add a signature box, then share the downloaded file.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "sign",
    accent: "t-orange",
  },
  protect: {
    title: "Protect PDF",
    heading: "PROTECT PDF",
    kicker: "Sign",
    desc: "Encrypt the PDF with an open password using AES-256 in your browser.",
    accept: "application/pdf",
    hint: "PDF files",
    workspace: "protect",
    accent: "t-azure",
  },
  convert: {
    title: "Convert PDF",
    heading: "CONVERT PDF",
    kicker: "Convert",
    desc: "Convert PDF pages to images, or turn images into a PDF.",
    accept: "application/pdf,image/png,image/jpeg",
    hint: "PDF or image files",
    workspace: "convert",
    accent: "t-steel",
  },
};
